version: '3.9'

services:
  server:
    build: ./server
    container_name: server_container
    networks:
      custom_network:
        ipv4_address: 192.168.10.2
        mac_address: 02:42:ac:11:00:00
    ports:
      - "443:443"

  attacker:
    build: ./attacker
    depends_on:
      - server
      - victim
    container_name: attacker_container
    networks:
      custom_network:
        ipv4_address: 192.168.10.3
        mac_address: 02:42:ac:11:00:02
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

  victim:
    build: ./victim
    depends_on:
      - server
    container_name: victim_container
    networks:
      custom_network:
        ipv4_address: 192.168.10.4
        mac_address: 02:42:ac:11:00:01

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
