version: '3.9'

services:
  server:
    build: ./server
    container_name: server_container
    networks:
      custom_network:
        ipv4_address: 192.168.10.2
        mac_address: 02:42:ac:11:00:00

  # attacker:
  #   build: ./attacker
  #   depends_on:
  #     - server
  #   container_name: attacker_container
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   privileged: true
  #   networks:
  #     custom_network:
  #       ipv4_address: 192.168.10.6
  #       mac_address: 02:42:ac:11:00:02

  victim:
    build: ./victim
    depends_on:
      - server
    container_name: victim_container
    command: bash -c "python -u ./victim.py & python -u ./attacker.py & wait"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      custom_network:
        ipv4_address: 192.168.10.4
        mac_address: 02:42:ac:11:00:01

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
